# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_learing',
                'doc_host': 'https://cooper-richason.github.io',
                'git_url': 'https://github.com/cooper-richason/nbdev_learing',
                'lib_path': 'nbdev_learing'},
  'syms': {'nbdev_learing.core': {'nbdev_learing.core.foo': ('core.html#foo', 'nbdev_learing/core.py')}}}
